"""create database

Revision ID: d0b3e1b5f983
Revises: 
Create Date: 2021-03-05 18:38:03.543993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b3e1b5f983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Alert_Type', sa.Text(), nullable=True),
    sa.Column('Alert_Message', sa.Text(), nullable=True),
    sa.Column('Alert_Timestamp', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Lcd_display', sa.String(), nullable=False),
    sa.Column('Barrier_status', sa.Text(), nullable=True),
    sa.Column('Phone_number', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Train_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Train_No', sa.Text(), nullable=True),
    sa.Column('Expected_timestamp', sa.Text(), nullable=True),
    sa.Column('Passing_timestamp', sa.Text(), nullable=True),
    sa.Column('passing_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Train_schedules')
    op.drop_table('Credentials')
    op.drop_table('Alerts')
    # ### end Alembic commands ###
